### ISSUE TITLE
'GIT_COMMITTER_NAME' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by mnkgithub** [bdo/gitpair#18] opened 2018-10-17 10:50 UTC
Hi, 
I am trying to adopt gitpair for one of my project and followed the installation steps as mentioned. I've kept the .gitpair in home folder. I am getting below error when I try to commit. Can you help?

git commit -am "@mansoor @mahesh gitpair 13th try"
[GITPAIR] Author's full match: '@mansoor @mahesh '
[GITPAIR] Commit message: @mansoor @mahesh gitpair 13th try
[GITPAIR] Message without authors: gitpair 13th try
[GITPAIR] Reformatted message: MANSOOR|MAHESH: gitpair 13th try
[GITPAIR] 2 authors: Mansoor Nawaskhan and Mahesh Krishnamurthy
[GITPAIR] Randomly selected author: Mahesh Krishnamurthy
[GITPAIR] Randomly selected committer: Mansoor Nawaskhan
'GIT_COMMITTER_NAME' is not recognized as an internal or external command,
operable program or batch file.

C:\..............\.git\hooks\post-commit:88
      error(error);
      ^

TypeError: error is not a function
    at exec (C:\............\.git\hooks\post-commit:88:7)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[dev-version deb7f33] @mansoor @mahesh gitpair 13th try
 3 files changed, 7 insertions(+), 5 deletions(-)

**Comment by bdo** [comment] 2019-04-25 09:49
Hi @mnkgithub!

Thanks for reporting the bug and sorry for not seeing your issue sooner. I've been busy and haven't taken the time to look at the project for a while until recently.

Have you managed to find a solution to your problem?

If not let me know and we can work things out. 😄 

Cheers

**Comment by bdo** [comment] 2019-07-13 13:22
Closing this issue for now as I could not reproduce it.
@mnkgithub: feel free to re-open when you get a chance, if the bug is not fixed.

**Closed by bdo** 2019-07-13 13:22 UTC
Labels: bug
